# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /dssg/home/cln04/01.software/miniconda3/envs/mygcc/bin/cmake

# The command to remove a file.
RM = /dssg/home/cln04/01.software/miniconda3/envs/mygcc/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /dssg/home/cln04/02.scripts/Clion/Polymorphism/Employee

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /dssg/home/cln04/02.scripts/Clion/Polymorphism/Employee

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/dssg/home/cln04/01.software/miniconda3/envs/mygcc/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/dssg/home/cln04/01.software/miniconda3/envs/mygcc/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /dssg/home/cln04/02.scripts/Clion/Polymorphism/Employee/CMakeFiles /dssg/home/cln04/02.scripts/Clion/Polymorphism/Employee//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /dssg/home/cln04/02.scripts/Clion/Polymorphism/Employee/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Employee

# Build rule for target.
Employee: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Employee
.PHONY : Employee

# fast build rule for target.
Employee/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Employee.dir/build.make CMakeFiles/Employee.dir/build
.PHONY : Employee/fast

BasePlusCommissionEmployee.o: BasePlusCommissionEmployee.cpp.o
.PHONY : BasePlusCommissionEmployee.o

# target to build an object file
BasePlusCommissionEmployee.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Employee.dir/build.make CMakeFiles/Employee.dir/BasePlusCommissionEmployee.cpp.o
.PHONY : BasePlusCommissionEmployee.cpp.o

BasePlusCommissionEmployee.i: BasePlusCommissionEmployee.cpp.i
.PHONY : BasePlusCommissionEmployee.i

# target to preprocess a source file
BasePlusCommissionEmployee.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Employee.dir/build.make CMakeFiles/Employee.dir/BasePlusCommissionEmployee.cpp.i
.PHONY : BasePlusCommissionEmployee.cpp.i

BasePlusCommissionEmployee.s: BasePlusCommissionEmployee.cpp.s
.PHONY : BasePlusCommissionEmployee.s

# target to generate assembly for a file
BasePlusCommissionEmployee.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Employee.dir/build.make CMakeFiles/Employee.dir/BasePlusCommissionEmployee.cpp.s
.PHONY : BasePlusCommissionEmployee.cpp.s

CommissionEmployee.o: CommissionEmployee.cpp.o
.PHONY : CommissionEmployee.o

# target to build an object file
CommissionEmployee.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Employee.dir/build.make CMakeFiles/Employee.dir/CommissionEmployee.cpp.o
.PHONY : CommissionEmployee.cpp.o

CommissionEmployee.i: CommissionEmployee.cpp.i
.PHONY : CommissionEmployee.i

# target to preprocess a source file
CommissionEmployee.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Employee.dir/build.make CMakeFiles/Employee.dir/CommissionEmployee.cpp.i
.PHONY : CommissionEmployee.cpp.i

CommissionEmployee.s: CommissionEmployee.cpp.s
.PHONY : CommissionEmployee.s

# target to generate assembly for a file
CommissionEmployee.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Employee.dir/build.make CMakeFiles/Employee.dir/CommissionEmployee.cpp.s
.PHONY : CommissionEmployee.cpp.s

Employee.o: Employee.cpp.o
.PHONY : Employee.o

# target to build an object file
Employee.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Employee.dir/build.make CMakeFiles/Employee.dir/Employee.cpp.o
.PHONY : Employee.cpp.o

Employee.i: Employee.cpp.i
.PHONY : Employee.i

# target to preprocess a source file
Employee.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Employee.dir/build.make CMakeFiles/Employee.dir/Employee.cpp.i
.PHONY : Employee.cpp.i

Employee.s: Employee.cpp.s
.PHONY : Employee.s

# target to generate assembly for a file
Employee.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Employee.dir/build.make CMakeFiles/Employee.dir/Employee.cpp.s
.PHONY : Employee.cpp.s

SalariedEmployee.o: SalariedEmployee.cpp.o
.PHONY : SalariedEmployee.o

# target to build an object file
SalariedEmployee.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Employee.dir/build.make CMakeFiles/Employee.dir/SalariedEmployee.cpp.o
.PHONY : SalariedEmployee.cpp.o

SalariedEmployee.i: SalariedEmployee.cpp.i
.PHONY : SalariedEmployee.i

# target to preprocess a source file
SalariedEmployee.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Employee.dir/build.make CMakeFiles/Employee.dir/SalariedEmployee.cpp.i
.PHONY : SalariedEmployee.cpp.i

SalariedEmployee.s: SalariedEmployee.cpp.s
.PHONY : SalariedEmployee.s

# target to generate assembly for a file
SalariedEmployee.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Employee.dir/build.make CMakeFiles/Employee.dir/SalariedEmployee.cpp.s
.PHONY : SalariedEmployee.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Employee.dir/build.make CMakeFiles/Employee.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Employee.dir/build.make CMakeFiles/Employee.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Employee.dir/build.make CMakeFiles/Employee.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Employee"
	@echo "... BasePlusCommissionEmployee.o"
	@echo "... BasePlusCommissionEmployee.i"
	@echo "... BasePlusCommissionEmployee.s"
	@echo "... CommissionEmployee.o"
	@echo "... CommissionEmployee.i"
	@echo "... CommissionEmployee.s"
	@echo "... Employee.o"
	@echo "... Employee.i"
	@echo "... Employee.s"
	@echo "... SalariedEmployee.o"
	@echo "... SalariedEmployee.i"
	@echo "... SalariedEmployee.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

